version: "3.1"

services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    environment:
      # Defualt username is postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_dev
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.7.7
    container_name: adminer
    restart: always
    ports:
      - 4000:8080
